-- ============================================================
-- Warhammer Paint Inventory — add P3 Formula brand + more
-- Vallejo / Army Painter equivalents
-- Run in the Supabase SQL editor. Requires warhammer_paint_equivalents
-- to already exist (create_paint_equivalents.sql).
--
-- Sourced from redgrimm.github.io/paint-conversion/ (community colour-
-- distance conversion chart covering Vallejo Game, Vallejo Model, P3
-- Formula (Privateer Press), and Army Painter). All 104 Citadel paint
-- names cross-checked against warhammer_paint_master; 2 could not be
-- matched and were dropped rather than guessed:
--   - "Ceramite White" — not a real/current Citadel product in our list
--   - "Death Guard Armor" — no match in warhammer_paint_master (closest
--     is "Death Guard Green", a clearly different name — skipped rather
--     than risk a wrong mapping)
-- 4 name mismatches were corrected against the master list before
-- insert: Bugmans Glow -> Bugman's Glow, Death World Forest ->
-- Deathworld Forest, Emperors Children -> Emperor's Children,
-- Evil Suns Scarlet -> Evil Sunz Scarlet.
--
-- P3 Formula is a new brand (not previously tracked) — add it to the
-- Brands array in Pages/Equivalents.razor after running this.
--
-- Idempotent: uses the same (paint_id, brand, equivalent_name) unique
-- constraint as prior seeds, so safe to re-run. Vallejo/Army Painter
-- rows that duplicate existing entries are silently skipped.
-- ============================================================

-- ── Vallejo (204 pairs: Game + Model per paint) ─────────────
insert into public.warhammer_paint_equivalents (paint_id, brand, equivalent_name)
select m.paint_id, 'Vallejo', v.equivalent_name
from (values
('White Scar', 'Dead White'),
('White Scar', 'White'),
('Averland Sunset', 'Gold Yellow'),
('Averland Sunset', 'Golden Yellow'),
('Yriel Yellow', 'Sun Yellow'),
('Yriel Yellow', 'Deep Yellow'),
('Flash Gitz Yellow', 'Moon Yellow'),
('Flash Gitz Yellow', 'Lemon Yellow'),
('Jokaero Orange', 'Hot Orange'),
('Jokaero Orange', 'Scarlet'),
('Troll Slayer Orange', 'Orange Fire'),
('Troll Slayer Orange', 'Bright Orange'),
('Fire Dragon Bright', 'Bronze Fleshtone'),
('Fire Dragon Bright', 'Light Orange'),
('Mephiston Red', 'Gory Red'),
('Mephiston Red', 'Flat Red'),
('Evil Sunz Scarlet', 'Bloody Red'),
('Evil Sunz Scarlet', 'Carmine Red'),
('Wild Rider Red', 'Hot Orange'),
('Wild Rider Red', 'Scarlet'),
('Khorne Red', 'Terracota'),
('Khorne Red', 'Hull Red'),
('Wazdakka Red', 'Gory Red'),
('Wazdakka Red', 'German Cam. Medium Brown'),
('Squig Orange', 'Tan'),
('Squig Orange', 'Dark Red'),
('Screamer Pink', 'Warlord Purple'),
('Screamer Pink', 'Violet Red'),
('Pink Horror', 'Warlord Purple'),
('Pink Horror', 'Magenta'),
('Emperor''s Children', 'Tan'),
('Emperor''s Children', 'Sunset Red'),
('Naggaroth Night', 'Hexed Lichen'),
('Naggaroth Night', 'Violet'),
('Xereus Purple', 'Heavy Violet'),
('Xereus Purple', 'Royal Purple'),
('Genestealer Purple', 'Sombre Grey'),
('Genestealer Purple', 'Blue Violet'),
('Daemonette Hide', 'Sombre Grey'),
('Daemonette Hide', 'Azure'),
('Warpfiend Grey', 'Cold Grey'),
('Warpfiend Grey', 'Grey Green'),
('Slaanesh Grey', 'Stonewall Grey'),
('Slaanesh Grey', 'Medium Sea Grey'),
('Kantor Blue', 'Royal Purple'),
('Kantor Blue', 'Dark Prussian Blue'),
('Alaitoc Blue', 'Sombre Grey'),
('Alaitoc Blue', 'Royal Blue'),
('Hoeth Blue', 'Electric Blue'),
('Hoeth Blue', 'Azure'),
('Macragge Blue', 'Magic Blue'),
('Macragge Blue', 'Blue'),
('Altdorf Guard Blue', 'Magic Blue'),
('Altdorf Guard Blue', 'Royal Blue'),
('Calgar Blue', 'Sombre Grey'),
('Calgar Blue', 'Ultramarine'),
('Caledor Sky', 'Sombre Grey'),
('Caledor Sky', 'Flat Blue'),
('Teclis Blue', 'Electric Blue'),
('Teclis Blue', 'Azure'),
('Lothern Blue', 'Electric Blue'),
('Lothern Blue', 'Deep Sky Blue'),
('Thousand Sons Blue', 'Wolf Grey'),
('Thousand Sons Blue', 'Deep Sky Blue'),
('Ahriman Blue', 'Steel Grey'),
('Ahriman Blue', 'Turquoise'),
('The Fang', 'Turquoise'),
('The Fang', 'French Mirage Blue'),
('Russ Grey', 'Steel Grey'),
('Russ Grey', 'Grey Blue'),
('Fenrisian Grey', 'Wolf Grey'),
('Fenrisian Grey', 'Pastel Blue'),
('Stegadon Scale Green', 'Heavy Blue'),
('Stegadon Scale Green', 'Oxford Blue'),
('Sotek Green', 'Turquoise'),
('Sotek Green', 'Field Blue'),
('Temple Guard Blue', 'Foul Green'),
('Temple Guard Blue', 'Blue Green'),
('Thunderhawk Blue', 'Turquoise'),
('Thunderhawk Blue', 'Field Blue'),
('Incubi Darkness', 'Scurvy Green'),
('Incubi Darkness', 'Black Green'),
('Kabalite Green', 'Foul Green'),
('Kabalite Green', 'Park Green Flat'),
('Sybarite Green', 'Foul Green'),
('Sybarite Green', 'Light Green'),
('Caliban Green', 'Dark Green'),
('Caliban Green', 'Yellow Olive'),
('Warpstone Glow', 'Goblin Green'),
('Warpstone Glow', 'Medium Olive'),
('Moot Green', 'Scorpion Green'),
('Moot Green', 'Lime Green'),
('Waaagh! Flesh', 'Mutation Green'),
('Waaagh! Flesh', 'Flat Green'),
('Warboss Green', 'Goblin Green'),
('Warboss Green', 'Park Green Flat'),
('Skarsnik Green', 'Foul Green'),
('Skarsnik Green', 'Intermediate Green'),
('Castellan Green', 'Heavy Green'),
('Castellan Green', 'Reflective Green'),
('Deathworld Forest', 'Camoflage Green'),
('Deathworld Forest', 'Luftwaffe Cam. Green'),
('Loren Forest', 'Camoflage Green'),
('Loren Forest', 'Uniform Green'),
('Straken Green', 'Camoflage Green'),
('Straken Green', 'Olive Green'),
('Nurgling Green', 'Heavy Khaki'),
('Nurgling Green', 'Middlestone'),
('Elysian Green', 'Heavy Khaki'),
('Elysian Green', 'Golden Olive'),
('Ogryn Camo', 'Dead Flesh'),
('Ogryn Camo', 'Middlestone'),
('Zandri Dust', 'Heavy Khaki'),
('Zandri Dust', 'Dark Yellow'),
('Ushabti Bone', 'Pale Yellow'),
('Ushabti Bone', 'Sand Yellow'),
('Screaming Skull', 'Elfic Flesh'),
('Screaming Skull', 'Buff'),
('Flayed One Flesh', 'Bone White'),
('Flayed One Flesh', 'Beige'),
('Steel Legion Drab', 'Heavy Brown'),
('Steel Legion Drab', 'English Uniform'),
('Tallarn Sand', 'Heavy Gold Brown'),
('Tallarn Sand', 'Gold Brown'),
('Karak Stone', 'Dead Flesh'),
('Karak Stone', 'Iraqi Sand'),
('Bugman''s Glow', 'Tan'),
('Bugman''s Glow', 'Saddle Brown'),
('Cadian Fleshtone', 'Dwarf Skin'),
('Cadian Fleshtone', 'Light Brown'),
('Kislev Flesh', 'Bone White'),
('Kislev Flesh', 'Flat Flesh'),
('Ratskin Flesh', 'Heavy Skintone'),
('Ratskin Flesh', 'Orange Brown'),
('Bestigor Flesh', 'Bronze Fleshtone'),
('Bestigor Flesh', 'Beige Red'),
('Ungor Flesh', 'Bone White'),
('Ungor Flesh', 'Dark Flesh'),
('Mournfang Brown', 'Terracota'),
('Mournfang Brown', 'Hull Red'),
('Skrag Brown', 'Parasite Brown'),
('Skrag Brown', 'Flat Earth'),
('Deathclaw Brown', 'Dwarf Skin'),
('Deathclaw Brown', 'Orange Brown'),
('XV-88', 'Leather Brown'),
('XV-88', 'English Uniform'),
('Tau Light Ochre', 'Heavy Ochre'),
('Tau Light Ochre', 'Ochre Brown'),
('Balor Brown', 'Leather Brown'),
('Balor Brown', 'Flat Earth'),
('Zamesi Desert', 'Plague Brown'),
('Zamesi Desert', 'Dark Flesh'),
('Rhinox Hide', 'Dark Fleshtone'),
('Rhinox Hide', 'German Cam. Black Brown'),
('Doombull Brown', 'Terracota'),
('Doombull Brown', 'Hull Red'),
('Tuskgor Fur', 'Heavy Red'),
('Tuskgor Fur', 'Cavalry Brown'),
('Dryad Bark', 'Charred Brown'),
('Dryad Bark', 'Leather Brown'),
('Gorthor Brown', 'Heavy Sienna'),
('Gorthor Brown', 'Burnt Umber'),
('Baneblade Brown', 'Khaki'),
('Baneblade Brown', 'Tan Earth'),
('Mechanicus Standard Grey', 'Cold Grey'),
('Mechanicus Standard Grey', 'USA Olive Drab'),
('Dawnstone', 'Khaki'),
('Dawnstone', 'Dark Sea Grey'),
('Administratum Grey', 'Heavy Blue Grey'),
('Administratum Grey', 'Blue Grey Pale'),
('Celestra Grey', 'Heavy Blue Grey'),
('Celestra Grey', 'Light Sea Grey'),
('Ulthuan Grey', 'Verdigris'),
('Ulthuan Grey', 'Silver Grey'),
('Rakarth Flesh', 'Heavy Blue Grey'),
('Rakarth Flesh', 'Stone Grey'),
('Pallid Wych Flesh', 'Elfic Flesh'),
('Pallid Wych Flesh', 'Silver Grey'),
('Abaddon Black', 'Black'),
('Abaddon Black', 'Glossy Black'),
('Eshin Grey', 'Cold Grey'),
('Eshin Grey', 'Grey Green'),
('Skavenblight Dinge', 'Beasty Brown'),
('Skavenblight Dinge', 'Leather Brown'),
('Stormvermin Fur', 'Khaki'),
('Stormvermin Fur', 'German Cam. Pale Brown'),
('Dark Reaper', 'Cayman Green'),
('Dark Reaper', 'USA Olive Drab'),
('Baharroth Blue', 'Heavy Blue Grey'),
('Baharroth Blue', 'Pale Blue'),
('Blue Horror', 'Ghost Grey'),
('Blue Horror', 'Pale Grey Blue'),
('Dechala Lilac', 'Wolf Grey'),
('Dechala Lilac', 'Blue Grey Pale'),
('Dorn Yellow', 'Moon Yellow'),
('Dorn Yellow', 'Lemon Yellow'),
('Fulgrim Pink', 'Pale Flesh'),
('Fulgrim Pink', 'Sky Grey'),
('Gauss Blaster Green', 'Verdigris'),
('Gauss Blaster Green', 'Grey Grey'),
('Krieg Khaki', 'Dead Flesh'),
('Krieg Khaki', 'Pale Sand'),
('Lugganath Orange', 'Rosy Flesh'),
('Lugganath Orange', 'Salmon Rose')
) as v(citadel_name, equivalent_name)
join public.warhammer_paint_master m on m.name = v.citadel_name
on conflict (paint_id, brand, equivalent_name) do nothing;


-- ── P3 Formula (102 pairs, new brand) ───────────────────────
insert into public.warhammer_paint_equivalents (paint_id, brand, equivalent_name)
select m.paint_id, 'P3 Formula', v.equivalent_name
from (values
('White Scar', 'Morrow White'),
('Averland Sunset', 'Heartfire'),
('Yriel Yellow', 'Sulfuric Yellow'),
('Flash Gitz Yellow', 'Cygnus Yellow'),
('Jokaero Orange', 'Khador Red Base'),
('Troll Slayer Orange', 'Khardic Flesh'),
('Fire Dragon Bright', 'Khador Red Highlight'),
('Mephiston Red', 'Skorne Red'),
('Evil Sunz Scarlet', 'Skorne Red'),
('Wild Rider Red', 'Khador Red Base'),
('Khorne Red', 'Sanguine Base'),
('Wazdakka Red', 'Sanguine Base'),
('Squig Orange', 'Bloodstone'),
('Screamer Pink', 'Murderous Magenta'),
('Pink Horror', 'Murderous Magenta'),
('Emperor''s Children', 'Murderous Magenta'),
('Naggaroth Night', 'Exile Blue'),
('Xereus Purple', 'Beaten Purple'),
('Genestealer Purple', 'Cygnar Base Blue'),
('Daemonette Hide', 'Greatcoat Grey'),
('Warpfiend Grey', 'Greatcoat Grey'),
('Slaanesh Grey', 'Ironhull Grey'),
('Kantor Blue', 'Exile Blue'),
('Alaitoc Blue', 'Cygnar Base Blue'),
('Hoeth Blue', 'Cygnar Blue Highlight'),
('Macragge Blue', 'Exile Blue'),
('Altdorf Guard Blue', 'Cygnar Base Blue'),
('Calgar Blue', 'Cygnar Blue Highlight'),
('Caledor Sky', 'Cygnar Blue Highlight'),
('Teclis Blue', 'Cygnar Blue Highlight'),
('Lothern Blue', 'Ironhull Grey'),
('Thousand Sons Blue', 'Meredius Blue'),
('Ahriman Blue', 'Trollblood Base'),
('The Fang', 'Trollblood Base'),
('Russ Grey', 'Greatcoat Grey'),
('Fenrisian Grey', 'Ironhull Grey'),
('Stegadon Scale Green', 'Exile Blue'),
('Sotek Green', 'Coal Black'),
('Temple Guard Blue', 'Meredius Blue'),
('Thunderhawk Blue', 'Coal Black'),
('Incubi Darkness', 'Coal Black'),
('Kabalite Green', 'Gnarls Green'),
('Sybarite Green', 'Iosan Green'),
('Caliban Green', 'Cryx Bane Base'),
('Warpstone Glow', 'Gnarls Green'),
('Moot Green', 'Iosan Green'),
('Waaagh! Flesh', 'Gnarls Green'),
('Warboss Green', 'Gnarls Green'),
('Skarsnik Green', 'Traitor Green'),
('Castellan Green', 'Cryx Bane Base'),
('Deathworld Forest', 'Battledress Green'),
('Loren Forest', 'Ordic Olive'),
('Straken Green', 'Ordic Olive'),
('Nurgling Green', 'Traitor Green'),
('Elysian Green', 'Ordic Olive'),
('Ogryn Camo', 'Wurm Green'),
('Zandri Dust', 'Rucksack Tan'),
('Ushabti Bone', 'Hammerfall Khaki'),
('Screaming Skull', 'Jack Bone'),
('Flayed One Flesh', 'Jack Bone'),
('Steel Legion Drab', 'Thornwood Green'),
('Tallarn Sand', 'Gun Corps Brown'),
('Karak Stone', 'Beast Hide'),
('Bugman''s Glow', 'Idrian Flesh'),
('Cadian Fleshtone', 'Khardic Flesh'),
('Kislev Flesh', 'Midlund Flesh'),
('Ratskin Flesh', 'Idrian Flesh'),
('Bestigor Flesh', 'Khardic Flesh'),
('Ungor Flesh', 'Heartfire'),
('Mournfang Brown', 'Sanguine Base'),
('Skrag Brown', 'Bloodstone'),
('Deathclaw Brown', 'Khardic Flesh'),
('XV-88', 'Idrian Flesh'),
('Tau Light Ochre', 'Bloodtracker Brown'),
('Balor Brown', 'Bootstrap Leather'),
('Zamesi Desert', 'Moldy Ochre'),
('Rhinox Hide', 'Battlefield Brown'),
('Doombull Brown', 'Sanguine Base'),
('Tuskgor Fur', 'Skorne Red'),
('Dryad Bark', 'Battlefield Brown'),
('Gorthor Brown', 'Thornwood Green'),
('Baneblade Brown', 'Cryx Bane Highlight'),
('Mechanicus Standard Grey', 'Greatcoat Grey'),
('Dawnstone', 'Bastion Grey'),
('Administratum Grey', 'Ironhull Grey'),
('Celestra Grey', 'Ironhull Grey'),
('Ulthuan Grey', 'Underbelly Blue'),
('Rakarth Flesh', 'Trollblood Highlight'),
('Pallid Wych Flesh', 'Jack Bone'),
('Abaddon Black', 'Thamar Black'),
('Eshin Grey', 'Greatcoat Grey'),
('Skavenblight Dinge', 'Cryx Bane Base'),
('Stormvermin Fur', 'Bastion Grey'),
('Dark Reaper', 'Greatcoat Grey'),
('Baharroth Blue', 'Arcane Blue'),
('Blue Horror', 'Underbelly Blue'),
('Dechala Lilac', 'Ironhull Grey'),
('Dorn Yellow', 'Cygnus Yellow'),
('Fulgrim Pink', 'Carnal Pink'),
('Gauss Blaster Green', 'Arcane Blue'),
('Krieg Khaki', 'Hammerfall Khaki'),
('Lugganath Orange', 'Midlund Flesh')
) as v(citadel_name, equivalent_name)
join public.warhammer_paint_master m on m.name = v.citadel_name
on conflict (paint_id, brand, equivalent_name) do nothing;


-- ── Army Painter (102 pairs, supplements the existing 48) ───
insert into public.warhammer_paint_equivalents (paint_id, brand, equivalent_name)
select m.paint_id, 'Army Painter', v.equivalent_name
from (values
('White Scar', 'Matt White'),
('Averland Sunset', 'Phoenix Flames'),
('Yriel Yellow', 'Daemonic Yellow'),
('Flash Gitz Yellow', 'Babe Blonde'),
('Jokaero Orange', 'Mythical Orange'),
('Troll Slayer Orange', 'Fire Lizard'),
('Fire Dragon Bright', 'Barbarian Flesh'),
('Mephiston Red', 'Dragon Red'),
('Evil Sunz Scarlet', 'Pure Red'),
('Wild Rider Red', 'Pure Red'),
('Khorne Red', 'Chaotic Red'),
('Wazdakka Red', 'Dragon Red'),
('Squig Orange', 'Mars Red'),
('Screamer Pink', 'Vampire Red'),
('Pink Horror', 'Wasteland Soil'),
('Emperor''s Children', 'Orc Blood'),
('Naggaroth Night', 'Deep Blue'),
('Xereus Purple', 'Alien Purple'),
('Genestealer Purple', 'Dungeon Grey'),
('Daemonette Hide', 'Dungeon Grey'),
('Warpfiend Grey', 'Dungeon Grey'),
('Slaanesh Grey', 'Ash Grey'),
('Kantor Blue', 'Deep Blue'),
('Alaitoc Blue', 'Griffon Blue'),
('Hoeth Blue', 'Crystal Blue'),
('Macragge Blue', 'Ultramarine Blue'),
('Altdorf Guard Blue', 'Ultramarine Blue'),
('Calgar Blue', 'Viking Blue'),
('Caledor Sky', 'Viking Blue'),
('Teclis Blue', 'Crystal Blue'),
('Lothern Blue', 'Voidshield Blue'),
('Thousand Sons Blue', 'Voidshield Blue'),
('Ahriman Blue', 'Hydra Turquoise'),
('The Fang', 'Uniform Grey'),
('Russ Grey', 'Wolf Grey'),
('Fenrisian Grey', 'Ice Storm'),
('Stegadon Scale Green', 'Dark Sky'),
('Sotek Green', 'Wizards Orb'),
('Temple Guard Blue', 'Elemental Bolt'),
('Thunderhawk Blue', 'Uniform Grey'),
('Incubi Darkness', 'Necromance Cloak'),
('Kabalite Green', 'Elemental Bolt'),
('Sybarite Green', 'Goblin Green'),
('Caliban Green', 'Angel Green'),
('Warpstone Glow', 'Mouldy Clothes'),
('Moot Green', 'Jungle Green'),
('Waaagh! Flesh', 'Greenskin'),
('Warboss Green', 'Mouldy Clothes'),
('Skarsnik Green', 'Goblin Green'),
('Castellan Green', 'Elf Green'),
('Deathworld Forest', 'Army Green'),
('Loren Forest', 'Army Green'),
('Straken Green', 'Commando Green'),
('Nurgling Green', 'Scaly Hide'),
('Elysian Green', 'Witch Brew'),
('Ogryn Camo', 'Jungle Green'),
('Zandri Dust', 'Witch Brew'),
('Ushabti Bone', 'Necrotic Flesh'),
('Screaming Skull', 'Skeleton Bone'),
('Flayed One Flesh', 'Corpse Pale'),
('Steel Legion Drab', 'Venom Wyrm'),
('Tallarn Sand', 'Sulphide Ochre'),
('Karak Stone', 'Kobold Skin'),
('Bugman''s Glow', 'Werewolf Fur'),
('Cadian Fleshtone', 'Tanned Flesh'),
('Kislev Flesh', 'Kobold Skin'),
('Ratskin Flesh', 'Tanned Flesh'),
('Bestigor Flesh', 'Troll Claws'),
('Ungor Flesh', 'Kobold Skin'),
('Mournfang Brown', 'Chaotic Red'),
('Skrag Brown', 'Monster Brown'),
('Deathclaw Brown', 'Tanned Flesh'),
('XV-88', 'Leather Brown'),
('Tau Light Ochre', 'Fire Lizard'),
('Balor Brown', 'Monster Brown'),
('Zamesi Desert', 'Phoenix Flames'),
('Rhinox Hide', 'Dirt Spatter'),
('Doombull Brown', 'Chaotic Red'),
('Tuskgor Fur', 'Vampire Red'),
('Dryad Bark', 'Necromance Cloak'),
('Gorthor Brown', 'Dark Stone'),
('Baneblade Brown', 'Filthy Cape'),
('Mechanicus Standard Grey', 'Hardened Carapace'),
('Dawnstone', 'Field Grey'),
('Administratum Grey', 'Ash Grey'),
('Celestra Grey', 'Ash Grey'),
('Ulthuan Grey', 'Spaceship Exterior'),
('Rakarth Flesh', 'Ash Grey'),
('Pallid Wych Flesh', 'Drake Tooth'),
('Abaddon Black', 'Matt Black'),
('Eshin Grey', 'Dark Stone'),
('Skavenblight Dinge', 'Hardened Carapace'),
('Stormvermin Fur', 'Cultist Robe'),
('Dark Reaper', 'Necromance Cloak'),
('Baharroth Blue', 'Toxic Mist'),
('Blue Horror', 'Gorgon Hide'),
('Dechala Lilac', 'Oozing Purple'),
('Dorn Yellow', 'Babe Blonde'),
('Fulgrim Pink', 'Spaceship Exterior'),
('Gauss Blaster Green', 'Kraken Skin'),
('Krieg Khaki', 'Necrotic Flesh'),
('Lugganath Orange', 'Centaur Skin')
) as v(citadel_name, equivalent_name)
join public.warhammer_paint_master m on m.name = v.citadel_name
on conflict (paint_id, brand, equivalent_name) do nothing;
