-- ============================================================
-- Warhammer Paint Inventory — master paint list backup
-- Run once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- Idempotent: safe to run more than once.
--
-- This is a REFERENCE / BACKUP copy of the master paint list, not something
-- the app reads from — the app's source of truth stays the hardcoded list in
-- Models/PaintDatabase.cs (per your call to keep it there). This table exists
-- purely so the full name+type list also exists in the database in case
-- something happens to the code.
--
-- Generated directly from Models/PaintDatabase.cs (337 rows) — not retyped —
-- so it's guaranteed to match the app's actual data exactly.
-- ============================================================

create table if not exists public.warhammer_paint_master (
  paint_id bigint generated always as identity primary key,
  name     text not null,
  type     text not null,
  unique (name)
);

alter table public.warhammer_paint_master enable row level security;

grant select, insert, update, delete on public.warhammer_paint_master to anon;

drop policy if exists "anon read paint_master"   on public.warhammer_paint_master;
drop policy if exists "anon insert paint_master" on public.warhammer_paint_master;

create policy "anon read paint_master"
  on public.warhammer_paint_master for select
  to anon using (true);

create policy "anon insert paint_master"
  on public.warhammer_paint_master for insert
  to anon with check (true);

insert into public.warhammer_paint_master (name, type) values
  ('Abaddon Black', 'Base'),
  ('Averland Sunset', 'Base'),
  ('Balthasar Gold', 'Base'),
  ('Barak-Nar Burgundy', 'Base'),
  ('Bugman''s Glow', 'Base'),
  ('Caledor Sky', 'Base'),
  ('Caliban Green', 'Base'),
  ('Castellan Green', 'Base'),
  ('Catachan Flesh', 'Base'),
  ('Celestra Grey', 'Base'),
  ('Corax White', 'Base'),
  ('Corvus Black', 'Base'),
  ('Daemonette Hide', 'Base'),
  ('Death Guard Green', 'Base'),
  ('Death Korps Drab', 'Base'),
  ('Deathworld Forest', 'Base'),
  ('Dryad Bark', 'Base'),
  ('Gal Vorbak Red', 'Base'),
  ('Grey Knights Steel', 'Base'),
  ('Grey Seer', 'Base'),
  ('Hobgrot Hide', 'Base'),
  ('Incubi Darkness', 'Base'),
  ('Ionrach Skin', 'Base'),
  ('Iron Hands Steel', 'Base'),
  ('Iron Warriors', 'Base'),
  ('Jokaero Orange', 'Base'),
  ('Kantor Blue', 'Base'),
  ('Khorne Red', 'Base'),
  ('Leadbelcher', 'Base'),
  ('Lupercal Green', 'Base'),
  ('Macragge Blue', 'Base'),
  ('Mechanicus Standard Grey', 'Base'),
  ('Mephiston Red', 'Base'),
  ('Morghast Bone', 'Base'),
  ('Mournfang Brown', 'Base'),
  ('Naggaroth Night', 'Base'),
  ('Night Lords Blue', 'Base'),
  ('Nocturne Green', 'Base'),
  ('Orruk Flesh', 'Base'),
  ('Phoenician Purple', 'Base'),
  ('Rakarth Flesh', 'Base'),
  ('Ratskin Flesh', 'Base'),
  ('Retributor Armour', 'Base'),
  ('Rhinox Hide', 'Base'),
  ('Runelord Brass', 'Base'),
  ('Screamer Pink', 'Base'),
  ('Screaming Bell', 'Base'),
  ('Steel Legion Drab', 'Base'),
  ('Stegadon Scale Green', 'Base'),
  ('The Fang', 'Base'),
  ('Thondia Brown', 'Base'),
  ('Thousand Sons Blue', 'Base'),
  ('Waaagh! Flesh', 'Base'),
  ('Warplock Bronze', 'Base'),
  ('Wraithbone', 'Base'),
  ('XV-88', 'Base'),
  ('Zandri Dust', 'Base'),
  ('Administratum Grey', 'Layer'),
  ('Ahriman Blue', 'Layer'),
  ('Alaitoc Blue', 'Layer'),
  ('Altdorf Guard Blue', 'Layer'),
  ('Auric Armour Gold', 'Layer'),
  ('Baharroth Blue', 'Layer'),
  ('Balor Brown', 'Layer'),
  ('Baneblade Brown', 'Layer'),
  ('Bestigor Flesh', 'Layer'),
  ('Bloodreaver Flesh', 'Layer'),
  ('Blue Horror', 'Layer'),
  ('Brass Scorpion', 'Layer'),
  ('Cadian Fleshtone', 'Layer'),
  ('Calgar Blue', 'Layer'),
  ('Canoptek Alloy', 'Layer'),
  ('Castellax Bronze', 'Layer'),
  ('Dark Reaper', 'Layer'),
  ('Dawnstone', 'Layer'),
  ('Deathclaw Brown', 'Layer'),
  ('Dechala Lilac', 'Layer'),
  ('Deepkin Flesh', 'Layer'),
  ('Doombull Brown', 'Layer'),
  ('Dorn Yellow', 'Layer'),
  ('Elysian Green', 'Layer'),
  ('Emperor''s Children', 'Layer'),
  ('Eshin Grey', 'Layer'),
  ('Evil Sunz Scarlet', 'Layer'),
  ('Fenrisian Grey', 'Layer'),
  ('Fire Dragon Bright', 'Layer'),
  ('Flash Gitz Yellow', 'Layer'),
  ('Flayed One Flesh', 'Layer'),
  ('Fulgrim Pink', 'Layer'),
  ('Fulgurite Copper', 'Layer'),
  ('Gauss Blaster Green', 'Layer'),
  ('Gehenna''s Gold', 'Layer'),
  ('Genestealer Purple', 'Layer'),
  ('Gorthor Brown', 'Layer'),
  ('Hashut Copper', 'Layer'),
  ('Hoeth Blue', 'Layer'),
  ('Ironbreaker', 'Layer'),
  ('Kabalite Green', 'Layer'),
  ('Kakophoni Purple', 'Layer'),
  ('Karak Stone', 'Layer'),
  ('Kislev Flesh', 'Layer'),
  ('Knight-Questor Flesh', 'Layer'),
  ('Krieg Khaki', 'Layer'),
  ('Liberator Gold', 'Layer'),
  ('Loren Forest', 'Layer'),
  ('Lothern Blue', 'Layer'),
  ('Lugganath Orange', 'Layer'),
  ('Moot Green', 'Layer'),
  ('Nurgling Green', 'Layer'),
  ('Ogryn Camo', 'Layer'),
  ('Pallid Wych Flesh', 'Layer'),
  ('Phalanx Yellow', 'Layer'),
  ('Pink Horror', 'Layer'),
  ('Runefang Steel', 'Layer'),
  ('Russ Grey', 'Layer'),
  ('Screaming Skull', 'Layer'),
  ('Skarsnik Green', 'Layer'),
  ('Skavenblight Dinge', 'Layer'),
  ('Skrag Brown', 'Layer'),
  ('Skullcrusher Brass', 'Layer'),
  ('Slaanesh Grey', 'Layer'),
  ('Sotek Green', 'Layer'),
  ('Sons of Horus Green', 'Layer'),
  ('Squig Orange', 'Layer'),
  ('Stormhost Silver', 'Layer'),
  ('Stormvermin Fur', 'Layer'),
  ('Straken Green', 'Layer'),
  ('Sybarite Green', 'Layer'),
  ('Sycorax Bronze', 'Layer'),
  ('Tallarn Sand', 'Layer'),
  ('Tau Light Ochre', 'Layer'),
  ('Teclis Blue', 'Layer'),
  ('Temple Guard Blue', 'Layer'),
  ('Thunderhawk Blue', 'Layer'),
  ('Troll Slayer Orange', 'Layer'),
  ('Tuskgor Fur', 'Layer'),
  ('Ulthuan Grey', 'Layer'),
  ('Ungor Flesh', 'Layer'),
  ('Ushabti Bone', 'Layer'),
  ('Vulkan Green', 'Layer'),
  ('Warboss Green', 'Layer'),
  ('Warpfiend Grey', 'Layer'),
  ('Warpstone Glow', 'Layer'),
  ('Wazdakka Red', 'Layer'),
  ('White Scar', 'Layer'),
  ('Wild Rider Red', 'Layer'),
  ('Word Bearers Red', 'Layer'),
  ('Xereus Purple', 'Layer'),
  ('Yriel Yellow', 'Layer'),
  ('Zamesi Desert', 'Layer'),
  ('Aeldari Emerald', 'Contrast'),
  ('Aethermatic Blue', 'Contrast'),
  ('Aggaros Dunes', 'Contrast'),
  ('Akhelian Green', 'Contrast'),
  ('Apothecary White', 'Contrast'),
  ('Asurmen Blue', 'Contrast'),
  ('Bad Moon Yellow', 'Contrast'),
  ('Baal Red', 'Contrast'),
  ('Basilicanum Grey', 'Contrast'),
  ('Black Legion', 'Contrast'),
  ('Black Templar', 'Contrast'),
  ('Blood Angels Red', 'Contrast'),
  ('Briar Queen Chill', 'Contrast'),
  ('Celestium Blue', 'Contrast'),
  ('Creed Camo', 'Contrast'),
  ('Cygor Brown', 'Contrast'),
  ('Dark Angels Green', 'Contrast'),
  ('Darkoath Flesh', 'Contrast'),
  ('Doomfire Magenta', 'Contrast'),
  ('Dreadful Visage', 'Contrast'),
  ('Flesh Tearers Red', 'Contrast'),
  ('Frostheart', 'Contrast'),
  ('Fyreslayer Flesh', 'Contrast'),
  ('Garaghak''s Sewer', 'Contrast'),
  ('Gore-Grunta Fur', 'Contrast'),
  ('Gryph-Charger Grey', 'Contrast'),
  ('Gryph-Hound Orange', 'Contrast'),
  ('Guilliman Flesh', 'Contrast'),
  ('Gutrippa Flesh', 'Contrast'),
  ('Hexwraith Flame', 'Contrast'),
  ('Imperial Fist', 'Contrast'),
  ('Ironjawz Yellow', 'Contrast'),
  ('Iyanden Yellow', 'Contrast'),
  ('Karandras Green', 'Contrast'),
  ('Kroxigor Scales', 'Contrast'),
  ('Leviathan Purple', 'Contrast'),
  ('Leviadon Blue', 'Contrast'),
  ('Luxion Purple', 'Contrast'),
  ('Magmadroth Flame', 'Contrast'),
  ('Magos Purple', 'Contrast'),
  ('Mantis Warriors Green', 'Contrast'),
  ('Militarum Green', 'Contrast'),
  ('Nazdreg Yellow', 'Contrast'),
  ('Nighthaunt Gloom', 'Contrast'),
  ('Ork Flesh', 'Contrast'),
  ('Plaguebearer Flesh', 'Contrast'),
  ('Pylar Glacier', 'Contrast'),
  ('Ratling Grime', 'Contrast'),
  ('Shyish Purple', 'Contrast'),
  ('Sigvald Burgundy', 'Contrast'),
  ('Skeleton Horde', 'Contrast'),
  ('Snakebite Leather', 'Contrast'),
  ('Space Wolves Grey', 'Contrast'),
  ('Stormfiend', 'Contrast'),
  ('Striking Scorpion Green', 'Contrast'),
  ('Talassar Blue', 'Contrast'),
  ('Terradon Turquoise', 'Contrast'),
  ('Ultramarines Blue', 'Contrast'),
  ('Volupus Pink', 'Contrast'),
  ('Warp Lightning', 'Contrast'),
  ('Wyldwood', 'Contrast'),
  ('Astorath Red', 'Dry'),
  ('Changeling Pink', 'Dry'),
  ('Chronus Blue', 'Dry'),
  ('Eldar Flesh', 'Dry'),
  ('Etherium Blue', 'Dry'),
  ('Golden Griffon', 'Dry'),
  ('Golgfag Brown', 'Dry'),
  ('Hellion Green', 'Dry'),
  ('Hexos Palesun', 'Dry'),
  ('Imrik Blue', 'Dry'),
  ('Kindleflame', 'Dry'),
  ('Longbeard Grey', 'Dry'),
  ('Lucius Lilac', 'Dry'),
  ('Necron Compound', 'Dry'),
  ('Niblet Green', 'Dry'),
  ('Praxeti White', 'Dry'),
  ('Ryza Rust', 'Dry'),
  ('Sigmarite', 'Dry'),
  ('Skink Blue', 'Dry'),
  ('Stormfang', 'Dry'),
  ('Sylvaneth Bark', 'Dry'),
  ('Terminatus Stone', 'Dry'),
  ('Tyrant Skull', 'Dry'),
  ('Underhive Ash', 'Dry'),
  ('Verminlord Hide', 'Dry'),
  ('Wrack White', 'Dry'),
  ('Dry: Dawnstone', 'Dry'),
  ('Dry: Hoeth Blue', 'Dry'),
  ('Dry: Nurgling Green', 'Dry'),
  ('''Ardcoat', 'Technical'),
  ('Agrellan Badland', 'Technical'),
  ('Agrellan Earth', 'Technical'),
  ('Armageddon Dust', 'Technical'),
  ('Astrogranite', 'Technical'),
  ('Blood for the Blood God', 'Technical'),
  ('Contrast Medium', 'Technical'),
  ('Lahmian Medium', 'Technical'),
  ('Martian Ironcrust', 'Technical'),
  ('Martian Ironearth', 'Technical'),
  ('Mordant Earth', 'Technical'),
  ('Nihilakh Oxide', 'Technical'),
  ('Nurgle''s Rot', 'Technical'),
  ('Soulstone Blue', 'Technical'),
  ('Spiritstone Red', 'Technical'),
  ('Stirland Mud', 'Technical'),
  ('Stormshield', 'Technical'),
  ('Tesseract Glow', 'Technical'),
  ('Typhus Corrosion', 'Technical'),
  ('Valhallan Blizzard', 'Technical'),
  ('Waystone Green', 'Technical'),
  ('Agrax Earthshade', 'Shade'),
  ('Athonian Camoshade', 'Shade'),
  ('Berserker Bloodshade', 'Shade'),
  ('Biel-Tan Green', 'Shade'),
  ('Carroburg Crimson', 'Shade'),
  ('Casandora Yellow', 'Shade'),
  ('Coelia Greenshade', 'Shade'),
  ('Drakenhof Nightshade', 'Shade'),
  ('Druchii Violet', 'Shade'),
  ('Fuegan Orange', 'Shade'),
  ('Kroak Green', 'Shade'),
  ('Mortarion Grime', 'Shade'),
  ('Nuln Oil', 'Shade'),
  ('Poxwalker', 'Shade'),
  ('Reikland Fleshshade', 'Shade'),
  ('Seraphim Sepia', 'Shade'),
  ('Soulblight Grey', 'Shade'),
  ('Targor Rageshade', 'Shade'),
  ('Tyran Blue', 'Shade'),
  ('Air: Abaddon Black', 'Air'),
  ('Air: Administratum Grey', 'Air'),
  ('Air: Air Caste Thinner', 'Air'),
  ('Air: Angron Red Clear', 'Air'),
  ('Air: Averland Sunset', 'Air'),
  ('Air: Balthasar Gold', 'Air'),
  ('Air: Baneblade Brown', 'Air'),
  ('Air: Caliban Green', 'Air'),
  ('Air: Calth Blue Clear', 'Air'),
  ('Air: Castellan Green', 'Air'),
  ('Air: Corvus Black', 'Air'),
  ('Air: Dawnstone', 'Air'),
  ('Air: Deathworld Forest', 'Air'),
  ('Air: Eidolon Purple Clear', 'Air'),
  ('Air: Elysian Green', 'Air'),
  ('Air: Evil Sunz Scarlet', 'Air'),
  ('Air: Fenrisian Grey', 'Air'),
  ('Air: Flash Gitz Yellow', 'Air'),
  ('Air: Grey Knights Steel', 'Air'),
  ('Air: Kantor Blue', 'Air'),
  ('Air: Khorne Red', 'Air'),
  ('Air: Kislev Flesh', 'Air'),
  ('Air: Leadbelcher', 'Air'),
  ('Air: Lothern Blue', 'Air'),
  ('Air: Macragge Blue', 'Air'),
  ('Air: Mechanicus Standard Grey', 'Air'),
  ('Air: Mephiston Red', 'Air'),
  ('Air: Moot Green', 'Air'),
  ('Air: Mortarion Green Clear', 'Air'),
  ('Air: Mournfang Brown', 'Air'),
  ('Air: Night Lords Blue', 'Air'),
  ('Air: Ogryn Camo', 'Air'),
  ('Air: Phalanx Yellow', 'Air'),
  ('Air: Phoenician Purple', 'Air'),
  ('Air: Runefang Steel', 'Air'),
  ('Air: Russ Grey', 'Air'),
  ('Air: Temple Guard Blue', 'Air'),
  ('Air: Thallax Gold', 'Air'),
  ('Air: The Fang', 'Air'),
  ('Air: Troll Slayer Orange', 'Air'),
  ('Air: Typhon Ash', 'Air'),
  ('Air: Ulthuan Grey', 'Air'),
  ('Air: Ushabti Bone', 'Air'),
  ('Air: White Scar', 'Air'),
  ('Air: Zandri Dust', 'Air'),
  ('Spray: Chaos Black', 'Spray'),
  ('Spray: Death Guard Green', 'Spray'),
  ('Spray: Grey Seer', 'Spray'),
  ('Spray: Leadbelcher', 'Spray'),
  ('Spray: Macragge Blue', 'Spray'),
  ('Spray: Mechanicus Standard Grey', 'Spray'),
  ('Spray: Mephiston Red', 'Spray'),
  ('Spray: Munitorum Varnish', 'Spray'),
  ('Spray: Retributor Armour', 'Spray'),
  ('Spray: White Scar', 'Spray'),
  ('Spray: Wraithbone', 'Spray'),
  ('Spray: Zandri Dust', 'Spray')
on conflict (name) do nothing;
