namespace WarhamerPaintInventoryWeb.Pages;

public partial class Guides
{
    private static readonly List<Section> BlackTemplarsOverall =
    [
        new("Armour",
        [
            new("Basecoat", "Abaddon Black"),
            new("Recess Shade", "Nuln Oil"),
            new("Layer / Drybrush", "Eshin Grey"),
            new("Edge Highlight", "Fenrisian Grey"),
        ]),
        new("Trim & Metal",
        [
            new("Basecoat", "Leadbelcher"),
            new("Shade", "Nuln Oil"),
            new("Edge Highlight", "Stormhost Silver"),
        ]),
        new("Robes / Bone",
        [
            new("Basecoat", "Corax White"),
            new("Shade", "Agrax Earthshade"),
            new("Edge Highlight", "White Scar"),
        ]),
        new("Base / Rims",
        [
            new("Rim", "Auric Armour Gold"),
            new("Basing", "Stirland Mud", "with Astrogranite Debris"),
        ]),
    ];

    private static FactionGuide BuildBlackTemplars() => new("Black Templars",
    [
        new("Overall (Head-to-Toe)", null, BlackTemplarsOverall, IsScheme: true),

        PlainUnit(BlackTemplarsOverall, "Captain"),
        PlainUnit(BlackTemplarsOverall, "Captain in Gravis Armour"),
        PlainUnit(BlackTemplarsOverall, "Captain in Phobos Armour"),
        PlainUnit(BlackTemplarsOverall, "Captain in Terminator Armour"),
        PlainUnit(BlackTemplarsOverall, "Captain with Jump Pack"),
        PlainUnit(BlackTemplarsOverall, "Chaplain"),
        PlainUnit(BlackTemplarsOverall, "Chaplain in Terminator Armour"),
        PlainUnit(BlackTemplarsOverall, "Chaplain on Bike"),
        PlainUnit(BlackTemplarsOverall, "Chaplain with Jump Pack"),
        PlainUnit(BlackTemplarsOverall, "Lieutenant"),
        PlainUnit(BlackTemplarsOverall, "Lieutenant in Phobos Armour"),
        PlainUnit(BlackTemplarsOverall, "Lieutenant in Reiver Armour"),
        PlainUnit(BlackTemplarsOverall, "Lieutenant with Combi-weapon"),
        PlainUnit(BlackTemplarsOverall, "Apothecary"),
        PlainUnit(BlackTemplarsOverall, "Apothecary Biologis"),
        PlainUnit(BlackTemplarsOverall, "Ancient"),
        PlainUnit(BlackTemplarsOverall, "Ancient in Terminator Armour"),
        PlainUnit(BlackTemplarsOverall, "Bladeguard Ancient"),
        PlainUnit(BlackTemplarsOverall, "Judiciar"),
        PlainUnit(BlackTemplarsOverall, "Techmarine"),
        PlainUnit(BlackTemplarsOverall, "Castellan"),
        PlainUnit(BlackTemplarsOverall, "Chaplain Grimaldus"),
        PlainUnit(BlackTemplarsOverall, "Crusade Ancient"),
        PlainUnit(BlackTemplarsOverall, "Emperor's Champion"),
        PlainUnit(BlackTemplarsOverall, "Execrator"),
        PlainUnit(BlackTemplarsOverall, "High Marshal Helbrecht"),
        PlainUnit(BlackTemplarsOverall, "Marshal"),

        PlainUnit(BlackTemplarsOverall, "Assault Intercessor Squad"),
        PlainUnit(BlackTemplarsOverall, "Crusader Squad"),
        PlainUnit(BlackTemplarsOverall, "Heavy Intercessor Squad"),
        PlainUnit(BlackTemplarsOverall, "Intercessor Squad"),
        PlainUnit(BlackTemplarsOverall, "Tactical Squad"),

        PlainUnit(BlackTemplarsOverall, "Aggressor Squad"),
        PlainUnit(BlackTemplarsOverall, "Assault Intercessors With Jump Packs"),
        PlainUnit(BlackTemplarsOverall, "Bladeguard Veteran Squad"),
        PlainUnit(BlackTemplarsOverall, "Centurion Assault Squad"),
        PlainUnit(BlackTemplarsOverall, "Centurion Devastator Squad"),
        PlainUnit(BlackTemplarsOverall, "Company Heroes"),
        PlainUnit(BlackTemplarsOverall, "Desolation Squad"),
        PlainUnit(BlackTemplarsOverall, "Devastator Squad"),
        PlainUnit(BlackTemplarsOverall, "Eliminator Squad"),
        PlainUnit(BlackTemplarsOverall, "Eradicator Squad"),
        PlainUnit(BlackTemplarsOverall, "Hellblaster Squad"),
        PlainUnit(BlackTemplarsOverall, "Inceptor Squad"),
        PlainUnit(BlackTemplarsOverall, "Incursor Squad"),
        PlainUnit(BlackTemplarsOverall, "Infernus Squad"),
        PlainUnit(BlackTemplarsOverall, "Infiltrator Squad"),
        PlainUnit(BlackTemplarsOverall, "Outrider Squad"),
        PlainUnit(BlackTemplarsOverall, "Reiver Squad"),
        PlainUnit(BlackTemplarsOverall, "Scout Squad"),
        PlainUnit(BlackTemplarsOverall, "Sternguard Veteran Squad"),
        PlainUnit(BlackTemplarsOverall, "Suppressor Squad"),
        PlainUnit(BlackTemplarsOverall, "Sword Brethren Squad"),
        PlainUnit(BlackTemplarsOverall, "Terminator Assault Squad"),
        PlainUnit(BlackTemplarsOverall, "Terminator Squad"),
        PlainUnit(BlackTemplarsOverall, "Vanguard Veteran Squad With Jump Packs"),

        PlainUnit(BlackTemplarsOverall, "Drop Pod"),
        PlainUnit(BlackTemplarsOverall, "Impulsor"),
        PlainUnit(BlackTemplarsOverall, "Invader ATV"),
        PlainUnit(BlackTemplarsOverall, "Land Raider"),
        PlainUnit(BlackTemplarsOverall, "Land Raider Crusader"),
        PlainUnit(BlackTemplarsOverall, "Land Raider Redeemer"),
        PlainUnit(BlackTemplarsOverall, "Land Speeder"),
        PlainUnit(BlackTemplarsOverall, "Predator Annihilator"),
        PlainUnit(BlackTemplarsOverall, "Predator Destructor"),
        PlainUnit(BlackTemplarsOverall, "Razorback"),
        PlainUnit(BlackTemplarsOverall, "Rhino"),
        PlainUnit(BlackTemplarsOverall, "Storm Speeder Hailstrike"),
        PlainUnit(BlackTemplarsOverall, "Storm Speeder Hammerstrike"),
        PlainUnit(BlackTemplarsOverall, "Storm Speeder Thunderstrike"),
        PlainUnit(BlackTemplarsOverall, "Stormhawk Interceptor"),
        PlainUnit(BlackTemplarsOverall, "Stormraven Gunship"),
        PlainUnit(BlackTemplarsOverall, "Stormtalon Gunship"),
        PlainUnit(BlackTemplarsOverall, "Vindicator"),
        PlainUnit(BlackTemplarsOverall, "Whirlwind"),

        PlainUnit(BlackTemplarsOverall, "Ballistus Dreadnought"),
        PlainUnit(BlackTemplarsOverall, "Brutalis Dreadnought"),
        PlainUnit(BlackTemplarsOverall, "Dreadnought"),
        PlainUnit(BlackTemplarsOverall, "Invictor Tactical Warsuit"),
        PlainUnit(BlackTemplarsOverall, "Redemptor Dreadnought"),

        PlainUnit(BlackTemplarsOverall, "Firestrike Servo-turrets"),
        PlainUnit(BlackTemplarsOverall, "Hammerfall Bunker"),
    ]);
}
