namespace WarhamerPaintInventoryWeb.Pages;

public partial class Guides
{
    private static readonly List<Section> BloodAngelsOverall =
    [
        new("Armour",
        [
            new("Basecoat", "Mephiston Red"),
            new("Recess Shade", "Carroburg Crimson"),
            new("Layer", "Evil Sunz Scarlet"),
            new("Edge Highlight", "Wild Rider Red"),
        ]),
        new("Trim & Metal",
        [
            new("Basecoat", "Retributor Armour"),
            new("Shade", "Reikland Fleshshade"),
            new("Edge Highlight", "Auric Armour Gold"),
        ]),
        new("Details",
        [
            new("Black Panels / Eagle", "Abaddon Black", "Eshin Grey edge"),
            new("Bone / Parchment", "Ushabti Bone", "Agrax Earthshade wash"),
        ]),
        new("Base / Rims",
        [
            new("Rim", "Auric Armour Gold"),
            new("Basing", "Stirland Mud", "with Martian Ironearth"),
        ]),
    ];

    private static FactionGuide BuildBloodAngels() => new("Blood Angels",
    [
        new("Overall (Head-to-Toe)", null, BloodAngelsOverall, IsScheme: true),

        PlainUnit(BloodAngelsOverall, "Captain"),
        PlainUnit(BloodAngelsOverall, "Captain in Gravis Armour"),
        PlainUnit(BloodAngelsOverall, "Captain in Phobos Armour"),
        PlainUnit(BloodAngelsOverall, "Captain in Terminator Armour"),
        PlainUnit(BloodAngelsOverall, "Captain with Jump Pack"),
        PlainUnit(BloodAngelsOverall, "Chaplain"),
        PlainUnit(BloodAngelsOverall, "Chaplain in Terminator Armour"),
        PlainUnit(BloodAngelsOverall, "Chaplain on Bike"),
        PlainUnit(BloodAngelsOverall, "Chaplain with Jump Pack"),
        PlainUnit(BloodAngelsOverall, "Librarian"),
        PlainUnit(BloodAngelsOverall, "Librarian in Phobos Armour"),
        PlainUnit(BloodAngelsOverall, "Librarian in Terminator Armour"),
        PlainUnit(BloodAngelsOverall, "Lieutenant"),
        PlainUnit(BloodAngelsOverall, "Lieutenant in Phobos Armour"),
        PlainUnit(BloodAngelsOverall, "Lieutenant in Reiver Armour"),
        PlainUnit(BloodAngelsOverall, "Lieutenant with Combi-weapon"),
        PlainUnit(BloodAngelsOverall, "Apothecary"),
        PlainUnit(BloodAngelsOverall, "Apothecary Biologis"),
        PlainUnit(BloodAngelsOverall, "Ancient"),
        PlainUnit(BloodAngelsOverall, "Ancient in Terminator Armour"),
        PlainUnit(BloodAngelsOverall, "Bladeguard Ancient"),
        PlainUnit(BloodAngelsOverall, "Judiciar"),
        PlainUnit(BloodAngelsOverall, "Techmarine"),
        PlainUnit(BloodAngelsOverall, "Astorath"),
        PlainUnit(BloodAngelsOverall, "Blood Angels Captain"),
        PlainUnit(BloodAngelsOverall, "Chief Librarian Mephiston"),
        PlainUnit(BloodAngelsOverall, "Commander Dante"),
        PlainUnit(BloodAngelsOverall, "Death Company Captain"),
        PlainUnit(BloodAngelsOverall, "Death Company Captain with Jump Pack"),
        PlainUnit(BloodAngelsOverall, "Lemartes"),
        PlainUnit(BloodAngelsOverall, "Sanguinary Priest"),
        PlainUnit(BloodAngelsOverall, "The Sanguinor"),

        PlainUnit(BloodAngelsOverall, "Assault Intercessor Squad"),
        PlainUnit(BloodAngelsOverall, "Heavy Intercessor Squad"),
        PlainUnit(BloodAngelsOverall, "Intercessor Squad"),
        PlainUnit(BloodAngelsOverall, "Tactical Squad"),

        PlainUnit(BloodAngelsOverall, "Aggressor Squad"),
        PlainUnit(BloodAngelsOverall, "Assault Intercessors With Jump Packs"),
        PlainUnit(BloodAngelsOverall, "Bladeguard Veteran Squad"),
        PlainUnit(BloodAngelsOverall, "Centurion Assault Squad"),
        PlainUnit(BloodAngelsOverall, "Centurion Devastator Squad"),
        PlainUnit(BloodAngelsOverall, "Company Heroes"),
        PlainUnit(BloodAngelsOverall, "Death Company Marines"),
        PlainUnit(BloodAngelsOverall, "Death Company Marines with Bolt Rifles"),
        PlainUnit(BloodAngelsOverall, "Death Company Marines With Jump Packs"),
        PlainUnit(BloodAngelsOverall, "Desolation Squad"),
        PlainUnit(BloodAngelsOverall, "Devastator Squad"),
        PlainUnit(BloodAngelsOverall, "Eliminator Squad"),
        PlainUnit(BloodAngelsOverall, "Eradicator Squad"),
        PlainUnit(BloodAngelsOverall, "Hellblaster Squad"),
        PlainUnit(BloodAngelsOverall, "Inceptor Squad"),
        PlainUnit(BloodAngelsOverall, "Incursor Squad"),
        PlainUnit(BloodAngelsOverall, "Infernus Squad"),
        PlainUnit(BloodAngelsOverall, "Infiltrator Squad"),
        PlainUnit(BloodAngelsOverall, "Outrider Squad"),
        PlainUnit(BloodAngelsOverall, "Reiver Squad"),
        PlainUnit(BloodAngelsOverall, "Sanguinary Guard"),
        PlainUnit(BloodAngelsOverall, "Scout Squad"),
        PlainUnit(BloodAngelsOverall, "Sternguard Veteran Squad"),
        PlainUnit(BloodAngelsOverall, "Suppressor Squad"),
        PlainUnit(BloodAngelsOverall, "Terminator Assault Squad"),
        PlainUnit(BloodAngelsOverall, "Terminator Squad"),
        PlainUnit(BloodAngelsOverall, "Vanguard Veteran Squad With Jump Packs"),

        PlainUnit(BloodAngelsOverall, "Baal Predator"),
        PlainUnit(BloodAngelsOverall, "Drop Pod"),
        PlainUnit(BloodAngelsOverall, "Gladiator Lancer"),
        PlainUnit(BloodAngelsOverall, "Gladiator Reaper"),
        PlainUnit(BloodAngelsOverall, "Gladiator Valiant"),
        PlainUnit(BloodAngelsOverall, "Impulsor"),
        PlainUnit(BloodAngelsOverall, "Invader ATV"),
        PlainUnit(BloodAngelsOverall, "Land Raider"),
        PlainUnit(BloodAngelsOverall, "Land Raider Crusader"),
        PlainUnit(BloodAngelsOverall, "Land Raider Redeemer"),
        PlainUnit(BloodAngelsOverall, "Land Speeder"),
        PlainUnit(BloodAngelsOverall, "Predator Annihilator"),
        PlainUnit(BloodAngelsOverall, "Predator Destructor"),
        PlainUnit(BloodAngelsOverall, "Razorback"),
        PlainUnit(BloodAngelsOverall, "Repulsor"),
        PlainUnit(BloodAngelsOverall, "Repulsor Executioner"),
        PlainUnit(BloodAngelsOverall, "Rhino"),
        PlainUnit(BloodAngelsOverall, "Storm Speeder Hailstrike"),
        PlainUnit(BloodAngelsOverall, "Storm Speeder Hammerstrike"),
        PlainUnit(BloodAngelsOverall, "Storm Speeder Thunderstrike"),
        PlainUnit(BloodAngelsOverall, "Stormhawk Interceptor"),
        PlainUnit(BloodAngelsOverall, "Stormraven Gunship"),
        PlainUnit(BloodAngelsOverall, "Stormtalon Gunship"),
        PlainUnit(BloodAngelsOverall, "Vindicator"),
        PlainUnit(BloodAngelsOverall, "Whirlwind"),

        PlainUnit(BloodAngelsOverall, "Ballistus Dreadnought"),
        PlainUnit(BloodAngelsOverall, "Brutalis Dreadnought"),
        PlainUnit(BloodAngelsOverall, "Death Company Dreadnought"),
        PlainUnit(BloodAngelsOverall, "Dreadnought"),
        PlainUnit(BloodAngelsOverall, "Invictor Tactical Warsuit"),
        PlainUnit(BloodAngelsOverall, "Redemptor Dreadnought"),

        PlainUnit(BloodAngelsOverall, "Firestrike Servo-turrets"),
        PlainUnit(BloodAngelsOverall, "Hammerfall Bunker"),
    ]);
}
