namespace WarhamerPaintInventoryWeb.Pages;

public partial class Guides
{
    private static readonly List<Section> DarkAngelsOverall =
    [
        new("Armour",
        [
            new("Basecoat", "Caliban Green"),
            new("Recess Shade", "Nuln Oil"),
            new("Layer", "Caliban Green", "reapplied to raised panels"),
            new("Edge Highlight", "Warpstone Glow", "then a fine Moot Green line"),
        ]),
        new("Trim & Metal",
        [
            new("Basecoat", "Leadbelcher"),
            new("Shade", "Nuln Oil"),
            new("Edge Highlight", "Stormhost Silver"),
        ]),
        new("Details",
        [
            new("Bone Icons / Robes", "Ushabti Bone", "Agrax Earthshade wash"),
            new("Red Details", "Mephiston Red"),
        ]),
        new("Base / Rims",
        [
            new("Rim", "Auric Armour Gold"),
            new("Basing", "Stirland Mud", "with Astrogranite Debris"),
        ]),
    ];

    private static FactionGuide BuildDarkAngels() => new("Dark Angels",
    [
        new("Overall (Head-to-Toe)", null, DarkAngelsOverall, IsScheme: true),

        PlainUnit(DarkAngelsOverall, "Captain"),
        PlainUnit(DarkAngelsOverall, "Captain in Gravis Armour"),
        PlainUnit(DarkAngelsOverall, "Captain in Phobos Armour"),
        PlainUnit(DarkAngelsOverall, "Captain in Terminator Armour"),
        PlainUnit(DarkAngelsOverall, "Captain with Jump Pack"),
        PlainUnit(DarkAngelsOverall, "Chaplain"),
        PlainUnit(DarkAngelsOverall, "Chaplain in Terminator Armour"),
        PlainUnit(DarkAngelsOverall, "Chaplain on Bike"),
        PlainUnit(DarkAngelsOverall, "Chaplain with Jump Pack"),
        PlainUnit(DarkAngelsOverall, "Librarian"),
        PlainUnit(DarkAngelsOverall, "Librarian in Phobos Armour"),
        PlainUnit(DarkAngelsOverall, "Librarian in Terminator Armour"),
        PlainUnit(DarkAngelsOverall, "Lieutenant"),
        PlainUnit(DarkAngelsOverall, "Lieutenant in Phobos Armour"),
        PlainUnit(DarkAngelsOverall, "Lieutenant in Reiver Armour"),
        PlainUnit(DarkAngelsOverall, "Lieutenant with Combi-weapon"),
        PlainUnit(DarkAngelsOverall, "Apothecary"),
        PlainUnit(DarkAngelsOverall, "Apothecary Biologis"),
        PlainUnit(DarkAngelsOverall, "Ancient"),
        PlainUnit(DarkAngelsOverall, "Ancient in Terminator Armour"),
        PlainUnit(DarkAngelsOverall, "Bladeguard Ancient"),
        PlainUnit(DarkAngelsOverall, "Judiciar"),
        PlainUnit(DarkAngelsOverall, "Techmarine"),
        PlainUnit(DarkAngelsOverall, "Asmodai"),
        PlainUnit(DarkAngelsOverall, "Azrael"),
        PlainUnit(DarkAngelsOverall, "Belial"),
        PlainUnit(DarkAngelsOverall, "Ezekiel"),
        PlainUnit(DarkAngelsOverall, "Lazarus"),
        PlainUnit(DarkAngelsOverall, "Lion El'Jonson"),
        PlainUnit(DarkAngelsOverall, "Ravenwing Command Squad"),
        PlainUnit(DarkAngelsOverall, "Sammael"),

        PlainUnit(DarkAngelsOverall, "Assault Intercessor Squad"),
        PlainUnit(DarkAngelsOverall, "Heavy Intercessor Squad"),
        PlainUnit(DarkAngelsOverall, "Intercessor Squad"),
        PlainUnit(DarkAngelsOverall, "Tactical Squad"),

        PlainUnit(DarkAngelsOverall, "Aggressor Squad"),
        PlainUnit(DarkAngelsOverall, "Assault Intercessors With Jump Packs"),
        PlainUnit(DarkAngelsOverall, "Bladeguard Veteran Squad"),
        PlainUnit(DarkAngelsOverall, "Centurion Assault Squad"),
        PlainUnit(DarkAngelsOverall, "Centurion Devastator Squad"),
        PlainUnit(DarkAngelsOverall, "Company Heroes"),
        PlainUnit(DarkAngelsOverall, "Deathwing Knights"),
        PlainUnit(DarkAngelsOverall, "Deathwing Terminator Squad"),
        PlainUnit(DarkAngelsOverall, "Desolation Squad"),
        PlainUnit(DarkAngelsOverall, "Devastator Squad"),
        PlainUnit(DarkAngelsOverall, "Eliminator Squad"),
        PlainUnit(DarkAngelsOverall, "Eradicator Squad"),
        PlainUnit(DarkAngelsOverall, "Hellblaster Squad"),
        PlainUnit(DarkAngelsOverall, "Inceptor Squad"),
        PlainUnit(DarkAngelsOverall, "Incursor Squad"),
        PlainUnit(DarkAngelsOverall, "Infernus Squad"),
        PlainUnit(DarkAngelsOverall, "Infiltrator Squad"),
        PlainUnit(DarkAngelsOverall, "Inner Circle Companions"),
        PlainUnit(DarkAngelsOverall, "Outrider Squad"),
        PlainUnit(DarkAngelsOverall, "Ravenwing Black Knights"),
        PlainUnit(DarkAngelsOverall, "Reiver Squad"),
        PlainUnit(DarkAngelsOverall, "Scout Squad"),
        PlainUnit(DarkAngelsOverall, "Sternguard Veteran Squad"),
        PlainUnit(DarkAngelsOverall, "Suppressor Squad"),
        PlainUnit(DarkAngelsOverall, "Terminator Assault Squad"),
        PlainUnit(DarkAngelsOverall, "Terminator Squad"),
        PlainUnit(DarkAngelsOverall, "Vanguard Veteran Squad With Jump Packs"),

        PlainUnit(DarkAngelsOverall, "Drop Pod"),
        PlainUnit(DarkAngelsOverall, "Gladiator Lancer"),
        PlainUnit(DarkAngelsOverall, "Gladiator Reaper"),
        PlainUnit(DarkAngelsOverall, "Gladiator Valiant"),
        PlainUnit(DarkAngelsOverall, "Impulsor"),
        PlainUnit(DarkAngelsOverall, "Invader ATV"),
        PlainUnit(DarkAngelsOverall, "Land Raider"),
        PlainUnit(DarkAngelsOverall, "Land Raider Crusader"),
        PlainUnit(DarkAngelsOverall, "Land Raider Redeemer"),
        PlainUnit(DarkAngelsOverall, "Land Speeder"),
        PlainUnit(DarkAngelsOverall, "Land Speeder Vengeance"),
        PlainUnit(DarkAngelsOverall, "Nephilim Jetfighter"),
        PlainUnit(DarkAngelsOverall, "Predator Annihilator"),
        PlainUnit(DarkAngelsOverall, "Predator Destructor"),
        PlainUnit(DarkAngelsOverall, "Ravenwing Dark Talon"),
        PlainUnit(DarkAngelsOverall, "Ravenwing Darkshroud"),
        PlainUnit(DarkAngelsOverall, "Razorback"),
        PlainUnit(DarkAngelsOverall, "Repulsor"),
        PlainUnit(DarkAngelsOverall, "Repulsor Executioner"),
        PlainUnit(DarkAngelsOverall, "Rhino"),
        PlainUnit(DarkAngelsOverall, "Storm Speeder Hailstrike"),
        PlainUnit(DarkAngelsOverall, "Storm Speeder Hammerstrike"),
        PlainUnit(DarkAngelsOverall, "Storm Speeder Thunderstrike"),
        PlainUnit(DarkAngelsOverall, "Stormhawk Interceptor"),
        PlainUnit(DarkAngelsOverall, "Stormraven Gunship"),
        PlainUnit(DarkAngelsOverall, "Stormtalon Gunship"),
        PlainUnit(DarkAngelsOverall, "Vindicator"),
        PlainUnit(DarkAngelsOverall, "Whirlwind"),

        PlainUnit(DarkAngelsOverall, "Ballistus Dreadnought"),
        PlainUnit(DarkAngelsOverall, "Brutalis Dreadnought"),
        PlainUnit(DarkAngelsOverall, "Dreadnought"),
        PlainUnit(DarkAngelsOverall, "Invictor Tactical Warsuit"),
        PlainUnit(DarkAngelsOverall, "Redemptor Dreadnought"),

        PlainUnit(DarkAngelsOverall, "Firestrike Servo-turrets"),
        PlainUnit(DarkAngelsOverall, "Hammerfall Bunker"),
    ]);
}
