namespace WarhamerPaintInventoryWeb.Pages;

public partial class Guides
{
    private static readonly List<Section> SpaceWolvesOverall =
    [
        new("Armour",
        [
            new("Basecoat", "Dark Reaper"),
            new("Recess Shade", "Nuln Oil"),
            new("Layer", "Russ Grey"),
            new("Edge Highlight", "Fenrisian Grey"),
        ]),
        new("Trim & Metal",
        [
            new("Basecoat", "Leadbelcher"),
            new("Shade", "Nuln Oil"),
            new("Edge Highlight", "Runefang Steel"),
        ]),
        new("Details",
        [
            new("Fur / Pelts", "Rhinox Hide", "Baneblade Brown drybrush, Ushabti Bone highlight"),
            new("Yellow Trim", "White Scar", "Yriel Yellow layer"),
        ]),
        new("Base / Rims",
        [
            new("Rim", "Runefang Steel"),
            new("Basing", "Astrogranite Debris", "with Stirland Mud"),
        ]),
    ];

    private static FactionGuide BuildSpaceWolves() => new("Space Wolves",
    [
        new("Overall (Head-to-Toe)", null, SpaceWolvesOverall, IsScheme: true),

        PlainUnit(SpaceWolvesOverall, "Captain"),
        PlainUnit(SpaceWolvesOverall, "Captain in Gravis Armour"),
        PlainUnit(SpaceWolvesOverall, "Captain in Phobos Armour"),
        PlainUnit(SpaceWolvesOverall, "Captain in Terminator Armour"),
        PlainUnit(SpaceWolvesOverall, "Captain with Jump Pack"),
        PlainUnit(SpaceWolvesOverall, "Chaplain"),
        PlainUnit(SpaceWolvesOverall, "Chaplain in Terminator Armour"),
        PlainUnit(SpaceWolvesOverall, "Chaplain on Bike"),
        PlainUnit(SpaceWolvesOverall, "Chaplain with Jump Pack"),
        PlainUnit(SpaceWolvesOverall, "Librarian"),
        PlainUnit(SpaceWolvesOverall, "Librarian in Phobos Armour"),
        PlainUnit(SpaceWolvesOverall, "Librarian in Terminator Armour"),
        PlainUnit(SpaceWolvesOverall, "Lieutenant"),
        PlainUnit(SpaceWolvesOverall, "Lieutenant in Phobos Armour"),
        PlainUnit(SpaceWolvesOverall, "Lieutenant in Reiver Armour"),
        PlainUnit(SpaceWolvesOverall, "Lieutenant with Combi-weapon"),
        PlainUnit(SpaceWolvesOverall, "Ancient"),
        PlainUnit(SpaceWolvesOverall, "Ancient in Terminator Armour"),
        PlainUnit(SpaceWolvesOverall, "Bladeguard Ancient"),
        PlainUnit(SpaceWolvesOverall, "Judiciar"),
        PlainUnit(SpaceWolvesOverall, "Techmarine"),
        PlainUnit(SpaceWolvesOverall, "Arjac Rockfist"),
        PlainUnit(SpaceWolvesOverall, "Bjorn The Fell-Handed"),
        PlainUnit(SpaceWolvesOverall, "Iron Priest"),
        PlainUnit(SpaceWolvesOverall, "Logan Grimnar"),
        PlainUnit(SpaceWolvesOverall, "Murderfang"),
        PlainUnit(SpaceWolvesOverall, "Njal Stormcaller"),
        PlainUnit(SpaceWolvesOverall, "Ragnar Blackmane"),
        PlainUnit(SpaceWolvesOverall, "Ulrik The Slayer"),
        PlainUnit(SpaceWolvesOverall, "Wolf Guard Battle Leader"),
        PlainUnit(SpaceWolvesOverall, "Wolf Priest"),

        PlainUnit(SpaceWolvesOverall, "Assault Intercessor Squad"),
        PlainUnit(SpaceWolvesOverall, "Blood Claws"),
        PlainUnit(SpaceWolvesOverall, "Grey Hunters"),
        PlainUnit(SpaceWolvesOverall, "Heavy Intercessor Squad"),
        PlainUnit(SpaceWolvesOverall, "Intercessor Squad"),

        PlainUnit(SpaceWolvesOverall, "Aggressor Squad"),
        PlainUnit(SpaceWolvesOverall, "Assault Intercessors With Jump Packs"),
        PlainUnit(SpaceWolvesOverall, "Bladeguard Veteran Squad"),
        PlainUnit(SpaceWolvesOverall, "Centurion Assault Squad"),
        PlainUnit(SpaceWolvesOverall, "Centurion Devastator Squad"),
        PlainUnit(SpaceWolvesOverall, "Company Heroes"),
        PlainUnit(SpaceWolvesOverall, "Desolation Squad"),
        PlainUnit(SpaceWolvesOverall, "Eliminator Squad"),
        PlainUnit(SpaceWolvesOverall, "Eradicator Squad"),
        PlainUnit(SpaceWolvesOverall, "Fenrisian Wolves"),
        PlainUnit(SpaceWolvesOverall, "Hellblaster Squad"),
        PlainUnit(SpaceWolvesOverall, "Inceptor Squad"),
        PlainUnit(SpaceWolvesOverall, "Incursor Squad"),
        PlainUnit(SpaceWolvesOverall, "Infernus Squad"),
        PlainUnit(SpaceWolvesOverall, "Infiltrator Squad"),
        PlainUnit(SpaceWolvesOverall, "Outrider Squad"),
        PlainUnit(SpaceWolvesOverall, "Reiver Squad"),
        PlainUnit(SpaceWolvesOverall, "Scout Squad"),
        PlainUnit(SpaceWolvesOverall, "Sternguard Veteran Squad"),
        PlainUnit(SpaceWolvesOverall, "Suppressor Squad"),
        PlainUnit(SpaceWolvesOverall, "Terminator Assault Squad"),
        PlainUnit(SpaceWolvesOverall, "Terminator Squad"),
        PlainUnit(SpaceWolvesOverall, "Thunderwolf Cavalry"),
        PlainUnit(SpaceWolvesOverall, "Vanguard Veteran Squad With Jump Packs"),
        PlainUnit(SpaceWolvesOverall, "Wolf Guard Headtakers"),
        PlainUnit(SpaceWolvesOverall, "Wolf Guard Terminators"),
        PlainUnit(SpaceWolvesOverall, "Wolf Scouts"),
        PlainUnit(SpaceWolvesOverall, "Wulfen"),
        PlainUnit(SpaceWolvesOverall, "Wulfen with Storm Shields"),

        PlainUnit(SpaceWolvesOverall, "Drop Pod"),
        PlainUnit(SpaceWolvesOverall, "Gladiator Lancer"),
        PlainUnit(SpaceWolvesOverall, "Gladiator Reaper"),
        PlainUnit(SpaceWolvesOverall, "Gladiator Valiant"),
        PlainUnit(SpaceWolvesOverall, "Impulsor"),
        PlainUnit(SpaceWolvesOverall, "Invader ATV"),
        PlainUnit(SpaceWolvesOverall, "Land Raider"),
        PlainUnit(SpaceWolvesOverall, "Land Raider Crusader"),
        PlainUnit(SpaceWolvesOverall, "Land Raider Redeemer"),
        PlainUnit(SpaceWolvesOverall, "Land Speeder"),
        PlainUnit(SpaceWolvesOverall, "Predator Annihilator"),
        PlainUnit(SpaceWolvesOverall, "Predator Destructor"),
        PlainUnit(SpaceWolvesOverall, "Razorback"),
        PlainUnit(SpaceWolvesOverall, "Repulsor"),
        PlainUnit(SpaceWolvesOverall, "Repulsor Executioner"),
        PlainUnit(SpaceWolvesOverall, "Rhino"),
        PlainUnit(SpaceWolvesOverall, "Storm Speeder Hailstrike"),
        PlainUnit(SpaceWolvesOverall, "Storm Speeder Hammerstrike"),
        PlainUnit(SpaceWolvesOverall, "Storm Speeder Thunderstrike"),
        PlainUnit(SpaceWolvesOverall, "Stormhawk Interceptor"),
        PlainUnit(SpaceWolvesOverall, "Stormraven Gunship"),
        PlainUnit(SpaceWolvesOverall, "Stormtalon Gunship"),
        PlainUnit(SpaceWolvesOverall, "Vindicator"),
        PlainUnit(SpaceWolvesOverall, "Whirlwind"),

        PlainUnit(SpaceWolvesOverall, "Ballistus Dreadnought"),
        PlainUnit(SpaceWolvesOverall, "Brutalis Dreadnought"),
        PlainUnit(SpaceWolvesOverall, "Dreadnought"),
        PlainUnit(SpaceWolvesOverall, "Invictor Tactical Warsuit"),
        PlainUnit(SpaceWolvesOverall, "Redemptor Dreadnought"),
        PlainUnit(SpaceWolvesOverall, "Venerable Dreadnought"),
        PlainUnit(SpaceWolvesOverall, "Wulfen Dreadnought"),

        PlainUnit(SpaceWolvesOverall, "Firestrike Servo-turrets"),
        PlainUnit(SpaceWolvesOverall, "Hammerfall Bunker"),
    ]);
}
